// This file is generated by kxml_compiler from eagle2.xsd.
// All changes you do to this file will be lost.
#ifndef EAGLE2_H
#define EAGLE2_H

#include <QString>
#include <QDomElement>
#include <QXmlStreamWriter>

class Via
{
  public:
    enum ShapeEnum { Shape_square, Shape_round_asdas, Shape_octagon, Shape_Invalid };

  public:
    void setX( double v );
    double x() const;
    void setY( double v );
    double y() const;
    void setExtent( const QString &v );
    QString extent() const;
    void setDrill( double v );
    double drill() const;
    void setDiameter( double v );
    double diameter() const;
    void setShape( const ShapeEnum &v );
    Via::ShapeEnum shape() const;
    static QString shapeEnumToString( const ShapeEnum & v );
    /**
      Parse XML object from DOM element.
     */
    static Via parseElement( const QDomElement &element, bool *ok );
    void writeElement( QXmlStreamWriter &xml ) const;
    static Via parseFile( const QString &filename, bool *ok );
    static Via parseString( const QString &xml, bool *ok );
    bool writeFile( const QString &filename ) const;

  private:
    static Via::ShapeEnum shapeEnumFromString( const QString & v, bool *ok );

    double mX;
    double mY;
    QString mExtent;
    double mDrill;
    double mDiameter;
    ShapeEnum mShape;

    ShapeEnum shapeEnumFromString( const QString & v );
};

#endif
